name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t smatificia/smatificia-chatpdf .
      - name: Publish image to docker hub
        run: docker push smatificia/smatificia-chatpdf:latest   

  deploy: 
    needs: build
    runs-on: self-hosted    
    steps:
      - name: Pull image from docker hub
        run: docker pull smatificia/smatificia-chatpdf:latest 
      - name: Delete Old Container
        run: docker rm -f Chatpdf
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name Chatpdf smatificia/smatificia-chatpdf
